package com.kotlin.study.greendaogenlib;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;
import org.jetbrains.annotations.NotNull;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig momentDaoConfig;

    private final AccountDao accountDao;
    private final MomentDao momentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        momentDaoConfig = daoConfigMap.get(MomentDao.class).clone();
        momentDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        momentDao = new MomentDao(momentDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(Moment.class, momentDao);
    }
    
    public void clear() {
        accountDaoConfig.clearIdentityScope();
        momentDaoConfig.clearIdentityScope();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public MomentDao getMomentDao() {
        return momentDao;
    }

}
