package com.kotlin.study.greendaogenlib;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "MOMENT".
 */
@Entity
public class Moment {

    @Id
    private String id;
    private int type;
    private String text;

    @NotNull
    private java.util.Date time;

    @Generated
    public Moment() {
    }

    public Moment(String id) {
        this.id = id;
    }

    @Generated
    public Moment(String id, int type, String text, java.util.Date time) {
        this.id = id;
        this.type = type;
        this.text = text;
        this.time = time;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @NotNull
    public java.util.Date getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(@NotNull java.util.Date time) {
        this.time = time;
    }

}
