package com.kotlin.study.greendaogenlib;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOMENT".
*/
public class MomentDao extends AbstractDao<Moment, String> {

    public static final String TABLENAME = "MOMENT";

    /**
     * Properties of entity Moment.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Type = new Property(1, int.class, "type", false, "TYPE");
        public final static Property Text = new Property(2, String.class, "text", false, "TEXT");
        public final static Property Time = new Property(3, java.util.Date.class, "time", false, "TIME");
    }


    public MomentDao(DaoConfig config) {
        super(config);
    }
    
    public MomentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOMENT\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"TYPE\" INTEGER NOT NULL ," + // 1: type
                "\"TEXT\" TEXT," + // 2: text
                "\"TIME\" INTEGER NOT NULL );"); // 3: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOMENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Moment entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getType());
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(3, text);
        }
        stmt.bindLong(4, entity.getTime().getTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Moment entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getType());
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(3, text);
        }
        stmt.bindLong(4, entity.getTime().getTime());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Moment readEntity(Cursor cursor, int offset) {
        Moment entity = new Moment( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.getInt(offset + 1), // type
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // text
            new java.util.Date(cursor.getLong(offset + 3)) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Moment entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
        entity.setText(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTime(new java.util.Date(cursor.getLong(offset + 3)));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Moment entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Moment entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Moment entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
